### ISSUE TITLE
Found bug in setLikelihood function

### ISSUE THREAD

**Issue by sorawit112** [ryuichiueda/emcl2#3]
Hello sir,
I think it may be miss about i and j in loop iteration
This issue cause some map.yaml crash.

![Screenshot from 2022-08-01 12-26-22](https://user-images.githubusercontent.com/63549420/182078647-1acdaca6-41ab-4c78-aaec-7f86c87e480c.png)

**Comment by ryuichiueda** [comment]
Thank you very much. It may be a bug. Since I'm in a train now, could you please give me a pull request?

**Comment by ryuichiueda** [comment]
I fixed it by myself. Thank you!
